---
Name: productfeed
---
SilverShop\Page\Product:
  extensions:
    - Meldgaard\ProductFeed\ProductFeedExtension

SilverShop\Page\ProductVariation:
  extensions:
    - Meldgaard\ProductFeed\ProductFeedProductVariationExtension